version: '3.8'
services:
  redis-cluster:
    image: grokzen/redis-cluster:6.2.1
    #    restart: always
    environment:
      #      STANDALONE: 'true'
      SENTINEL: 'false'
      IP: '0.0.0.0'             # https://github.com/Grokzen/docker-redis-cluster#important-for-mac-users
      INITIAL_PORT: 7001
      MASTERS: 3
      SLAVES_PER_MASTER: 1
    ports:
      - '7001-7006:7001-7006'   # The cluster is 6 redis instances running with 3 master & 3 slaves, one slave for each master. They run on ports 7000 to 7005.
